name: NewSurvival
version: '${project.version}'
main: org.laykon.newsurvival.NewSurvival
api-version: '1.21'

commands:
  gma:
  gmc:
  gmsp:
  gms:
  ping:
  skills:
  repeat:
  serverexec:
  day:
  night:
  noon:
  sunrise:
  sunset:
  fly:
  stop:
  dev/skills/test-map:
